name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configure Git credentials
          git config --global user.email "deploy-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          
          # Add Hugging Face remote (replace YOUR_HF_USERNAME and YOUR_HF_SPACE_NAME)
          # Example: https://huggingface.co/spaces/john-doe/network-security-etl
          git remote add hf https://huggingface.co/spaces/Kuldeep13/network-security-etl
          
          # Push to Hugging Face Main branch (force push to overwrite the Space repo files)
          git push --force https://Kuldeep13:$HF_TOKEN@huggingface.co/spaces/Kuldeep13/network-security-etl main